# Generated by Django 4.1.1 on 2022-09-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zazinmori_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwd',
            field=models.CharField(db_column='passwd', max_length=1000),
        ),
    ]
