# Generated by Django 4.1.1 on 2022-09-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zazinmori_server', '0003_rename_user_user_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_info',
            new_name='Users_info',
        ),
    ]
