# Generated by Django 4.1.1 on 2022-09-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zazinmori_server', '0004_rename_user_info_users_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='reg_date',
            field=models.CharField(db_column='reg_date', max_length=200),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='update_date',
            field=models.CharField(db_column='update_date', max_length=200),
        ),
    ]
