# Generated by Django 4.1.1 on 2022-09-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zazinmori_server', '0005_alter_users_info_reg_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='birth',
            field=models.CharField(db_column='birthday', max_length=200),
        ),
    ]
