# Generated by Django 4.1.1 on 2022-09-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zazinmori_server', '0006_alter_users_info_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cvletter',
            name='member_id',
            field=models.CharField(db_column='member_id', max_length=45),
        ),
        migrations.AlterField(
            model_name='user_scraps',
            name='member_id',
            field=models.IntegerField(db_column='member_id'),
        ),
    ]
