# Generated by Django 4.1.1 on 2022-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zazinmori_server', '0007_alter_user_cvletter_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='date',
            field=models.CharField(db_column='date', max_length=200),
        ),
        migrations.AlterField(
            model_name='corp_finance',
            name='date',
            field=models.CharField(db_column='date', max_length=200),
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='end_date',
            field=models.CharField(db_column='end_date', max_length=200),
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='start_date',
            field=models.CharField(db_column='start_date', max_length=200),
        ),
        migrations.AlterField(
            model_name='passcvletter',
            name='employment_date',
            field=models.CharField(db_column='employment_date', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date',
            field=models.CharField(db_column='date', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_cvletter',
            name='update_date',
            field=models.CharField(db_column='update_date', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_cvletter',
            name='written_date',
            field=models.CharField(db_column='written_date', max_length=200),
        ),
    ]
